language: node_js

node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '4.0'
  - '4.1'

cache:
  directories:
    - node_modules

addons:
  postgresql: "9.3"

services:
  - postgresql

notifications:
  email:
    - jeremie.drouet@gmail.com

before_script:
  - PG_HOST=localhost PG_PORT=5432 sh test/pretest.sh
  - npm install
  - npm run build

script:
  - npm test

after_script:
  - cat coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
